import { YGOProPlayerChatMessage } from "./YGOProPlayerChatMessage";

// Wire format is the fixed, hand-verified sample below (not generated by the
// encoder under test): [size u16][0x19][player_type u16][utf16le msg 512 bytes].
//  - size  = 515 = 0x0203 little-endian (1 command + 2 player_type + 512 msg)
//  - type  = 0x10 = ChatColor.YELLOW, the legal "system message" value every
//    client-family renders (player_type 9 used to be silently dropped by
//    strictly-parsing ygopro clients).
//  - "维护测试" encodes as U+7EF4/U+62A4/U+6D4B/U+8BD5 little-endian.
describe("YGOProPlayerChatMessage", () => {
	it("broadcasts chat as STOC_CHAT with ChatColor.YELLOW system type", () => {
		const frame = YGOProPlayerChatMessage.create("维护测试");

		expect(frame.length).toBe(2 + 1 + 2 + 512);
		expect(frame.readUInt16LE(0)).toBe(515);
		expect(frame[2]).toBe(0x19);
		expect(frame.readUInt16LE(3)).toBe(0x10);
		expect(frame[3]).not.toBe(0x09);
	});

	it("keeps the message body UTF-16LE and zero-padded to 512 bytes", () => {
		const frame = YGOProPlayerChatMessage.create("维护测试");

		const bodyStart = 5;
		expect(frame.readUInt16LE(bodyStart + 0)).toBe(0x7ef4);
		expect(frame.readUInt16LE(bodyStart + 2)).toBe(0x62a4);
		expect(frame.readUInt16LE(bodyStart + 4)).toBe(0x6d4b);
		expect(frame.readUInt16LE(bodyStart + 6)).toBe(0x8bd5);
		expect(frame.subarray(bodyStart + 8)).toEqual(Buffer.alloc(504));
	});
});
